### ISSUE TITLE
callbacks

### ISSUE THREAD

**Issue by vonKristoff** [colinmeinke/svg-tween#3]
Hey - great tiny svg animator that does the job! Any chance for callbacks / promises ..?

**Comment by colinmeinke** [comment]
Hi, thanks for using svg tween, I'm glad you are finding it useful! What events are you looking for? There is a `complete` callback that you can pass into `tween` and `tweenPaths`.

I'm not planning on doing much more than bug fixes for this library as I'm currently working on a more powerful successor https://github.com/colinmeinke/wilderness.
