### ISSUE TITLE
Can't get examples to build

### ISSUE THREAD

**Issue by Blagoworks** [colinmeinke/svg-tween#4]
I get a build error with the examples, not sure what goes wrong. ReferenceError: Unknown plugin "transform-object-rest-spread". here's the contents of npm-debug-log.txt: 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild @0.0.0-semantically-released
6 info build @0.0.0-semantically-released
7 verbose unsafe-perm in lifecycle true
8 info @0.0.0-semantically-released Failed to exec build script
9 verbose stack Error: @0.0.0-semantically-released build: `browserify ./client.js -o ./client.dist.js -t babelify`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @0.0.0-semantically-released
11 verbose cwd F:\Development\Node\svg-tween-master\examples\batman
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error @0.0.0-semantically-released build: `browserify ./client.js -o ./client.dist.js -t babelify`
17 error Exit status 1
18 error Failed at the @0.0.0-semantically-released build script 'browserify ./client.js -o ./client.dist.js -t babelify'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     browserify ./client.js -o ./client.dist.js -t babelify
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by colinmeinke** [comment]
Hmm, for some reason babel is also picking up the package.json config in the root svg-tween directory, and if `npm install` has not been run in that directory also will throw the error.

I'd suggest, for now, to run `npm install` in the root svg tween directory as well.
